######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 2 23:34:09 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/dialogManager.h src/question.h src/questionDialog.h
SOURCES += src/main.cpp src/question.cpp src/questionDialog.cpp
